print *,"+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
print *,"                           compilation settings                    "
print *,"+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
print *," "
print *," +++++date (date):"
print *,"Fri Dec  6 10:24:42 EST 2013"
print *," "
print *," +++++Compiler: "
print *,"gfortran --version:"
print *,"GNU Fortran (GCC) 4.8.2"
print *,"Copyright (C) 2013 Free Software Foundation, Inc."
print *,""
print *,"GNU Fortran comes with NO WARRANTY, to the extent permitted by law."
print *,"You may redistribute copies of GNU Fortran"
print *,"under the terms of the GNU General Public License."
print *,"For more information about these matters, see the file named COPYING"
print *,""
print *," "
print *," +++++using Unix platform (uname -a): "
print *,"Linux laptop-yoga13 3.10.20-1-MANJARO #1 SMP Thu Nov 21 16:53:15 UTC 2013 x86_64 GNU/Linux"
print *," "
print *," +++++building sequence (make -n):"
print *,"make[1]: Entering directory '/home/nick/git/ncanestrari/shadow3'"
print *,"./shadow_version.sh gfortran"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_version.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_globaldefinitions.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c stringio.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c gfile.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_beamio.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_math.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_variables.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_kernel.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_synchrotron.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_pre_sync.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_preprocessors.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_postprocessors.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_bind_f.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow_crl.F90"
print *,"gfortran -cpp -fPIC -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4NIX -c shadow3.F90"
print *,"gfortran   -o shadow3 shadow3.o shadow_version.o shadow_globaldefinitions.o stringio.o gfile.o shadow_beamio.o shadow_math.o shadow_variables.o shadow_kernel.o shadow_synchrotron.o shadow_pre_sync.o shadow_preprocessors.o shadow_postprocessors.o shadow_bind_f.o shadow_crl.o "
print *,"make[1]: Leaving directory '/home/nick/git/ncanestrari/shadow3'"
print *,"+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
