print *,"+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
print *,"                           compilation settings                    "
print *,"+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
print *," "
print *," +++++date (date):"
print *,"Wed May 15 09:26:26 EDT 2013"
print *," "
print *," +++++Compiler: "
print *,"x86_64-w64-mingw32-gfortran --version:"
print *," "
print *," +++++using Unix platform (uname -a): "
print *,"Linux nsls2Canestrari 3.5.0-27-generic #46-Ubuntu SMP Mon Mar 25 19:58:17 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux"
print *," "
print *," +++++building sequence (make -n):"
print *,"make[1]: Entering directory `/home/ncanestrari/Projects/shadow3'"
print *,"./shadow_version.sh x86_64-w64-mingw32-gfortran"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_version.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_globaldefinitions.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c stringio.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c gfile.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_beamio.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_math.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_variables.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_kernel.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_synchrotron.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_pre_sync.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_preprocessors.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_postprocessors.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_bind_f.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow_crl.F90"
print *,"x86_64-w64-mingw32-gfortran -cpp -ffree-line-length-none  -static -static-libgfortran -static-libgcc -O2 -fomit-frame-pointer -D_COMPILE4WIN -c shadow3.F90"
print *,"x86_64-w64-mingw32-gfortran  -o shadow3.exe shadow3.o shadow_version.o shadow_globaldefinitions.o stringio.o gfile.o shadow_beamio.o shadow_math.o shadow_variables.o shadow_kernel.o shadow_synchrotron.o shadow_pre_sync.o shadow_preprocessors.o shadow_postprocessors.o shadow_bind_f.o shadow_crl.o "
print *,"make[1]: Leaving directory `/home/ncanestrari/Projects/shadow3'"
print *,"+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
